name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_INSTALL_DIR: '.\.dotnet'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache dotnet
      id: cache-dotnet
      uses: actions/cache@v3
      with:
        path: ${{ env.DOTNET_INSTALL_DIR }}
        key: ${{ runner.os }}-dotnet-10
        restore-keys: ${{ runner.os }}-dotnet-10

    - name: Setup dotnet
      if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 10.0.100-preview.5.25277.114

    - name: Setup node
      uses: actions/setup-node@v2
      
    - name: Cache NPM packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: ${{ env.DOTNET_INSTALL_DIR }}\dotnet run build.cs

    - name: Highlight
      env:
        TORCHLIGHT_TOKEN: ${{ secrets.TORCHLIGHT_TOKEN }}
      run: npx torchlight

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
